#!/usr/bin/env bash

BINARY=yq_linux_amd64
URI="https://api.github.com/repos/mikefarah/yq/releases/latest"

set -euo pipefail
[ -z "${DEBUG+x}" ] || { >&2 echo "${PS4}\"DEBUG\" environment variable set. Enabling debugging output."; set -x; }

function log() {
	>&2 echo "${@}"
}

function die() {
	log "FATAL ${@:-Unknown fatal error.}"
	exit 1
}

LATEST="$(curl -o - "${URI}" 2>/dev/null| jq .assets[].browser_download_url | grep "/${BINARY}\"$" | sed 's/"//g')" && [ -n "${LATEST}" ] || die "Failed to download and parse the latest version of \"${BINARY}\" from \"${URI}\"."

mkdir -p "${HOME}/.local/bin" || die "Failed to create local bin directory directory."

curl "${LATEST}" -Lo "${HOME}/.local/bin/yq" 2>/dev/null && chmod +x "${HOME}/.local/bin/yq" || die "Failed to download and install \"${BINARY}\"."
