#!/usr/bin/env bash

set -xeuo pipefail
[ -z "${DEBUG+x}" ] || { >&2 echo "${PS4}\"DEBUG\" environment variable is set. Enabling debugging output."; set -x; }

function log() {
	>&2 echo "${@:-}"
}

function die() {
	log "FATAL: ${@:-Unknown fatal error.}"
	exit 1
}

[ "${0}" == "./install" ] || die "This script assumes your working directory to be the root of the git repository."

mkdir -p ~/.config/containers/systemd || die "Could not create systend container directory."

units=($(ls systemd-units))
for f in "${units[@]}"; do
	ln -s "${PWD}/systemd-units/${f}" ~/.config/containers/systemd/"${f}" || die "Error symlinking file \"${f}\"."
done

systemctl --user daemon-reload
