#!/usr/bin/env bash

set -euo pipefail
[ -z "${DEBUG+x}" ] || { >&2 echo "${PS4}\"DEBUG\" environment variable is set. Enabling debugging output."; set -x; }

systemctl --user daemon-reload
systemctl --user start harbor-pod.service
